*
* Insert Random Customers
*
OPEN "DB.CUSTOMERS" TO POINTER.DB.CUSTOMERS ELSE STOP ("DB.CUSTOMERS Not found")
FOR I = 1 TO 10
  CALL SUBROUTINE.RANDOMSTRING(VAR.CUSTOMERNAME, 16)
  CALL SUBROUTINE.RANDOMSTRING(VAR.CUSTOMERADDR, 32)
  DIM ROW.CUSTOMER(2)
  ROW.CUSTOMER(1) = VAR.CUSTOMERNAME
  ROW.CUSTOMER(2) = VAR.CUSTOMERADDR
  MATWRITE ROW.CUSTOMER ON POINTER.DB.CUSTOMERS, I
NEXT I
