OPEN "DB.DATA" TO DB.DATA ELSE PRINT "DB.DATA Not found"
DICTKEY = "001"
READV A1 FROM DB.DATA, DICTKEY, 1 THEN PRINT A1 ELSE STOP
READV A2 FROM DB.DATA, DICTKEY, 2 THEN PRINT A2 ELSE STOP
PRINT \{"\ : DICTKEY : \":{"a1":"\ : A1 : \","a2":"\ : A2 : \"}}\
